//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Input/GameControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameControls"",
    ""maps"": [
        {
            ""name"": ""BuildMenu"",
            ""id"": ""ee713969-d970-4056-a226-c6662fe60cec"",
            ""actions"": [
                {
                    ""name"": ""ToggleBuildMenu"",
                    ""type"": ""Button"",
                    ""id"": ""c873cf05-170e-4d2a-a6c9-7625e0364711"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1bcb1f3f-66aa-4b12-a708-d7cdf4084336"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleBuildMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // BuildMenu
        m_BuildMenu = asset.FindActionMap("BuildMenu", throwIfNotFound: true);
        m_BuildMenu_ToggleBuildMenu = m_BuildMenu.FindAction("ToggleBuildMenu", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // BuildMenu
    private readonly InputActionMap m_BuildMenu;
    private IBuildMenuActions m_BuildMenuActionsCallbackInterface;
    private readonly InputAction m_BuildMenu_ToggleBuildMenu;
    public struct BuildMenuActions
    {
        private @GameControls m_Wrapper;
        public BuildMenuActions(@GameControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @ToggleBuildMenu => m_Wrapper.m_BuildMenu_ToggleBuildMenu;
        public InputActionMap Get() { return m_Wrapper.m_BuildMenu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BuildMenuActions set) { return set.Get(); }
        public void SetCallbacks(IBuildMenuActions instance)
        {
            if (m_Wrapper.m_BuildMenuActionsCallbackInterface != null)
            {
                @ToggleBuildMenu.started -= m_Wrapper.m_BuildMenuActionsCallbackInterface.OnToggleBuildMenu;
                @ToggleBuildMenu.performed -= m_Wrapper.m_BuildMenuActionsCallbackInterface.OnToggleBuildMenu;
                @ToggleBuildMenu.canceled -= m_Wrapper.m_BuildMenuActionsCallbackInterface.OnToggleBuildMenu;
            }
            m_Wrapper.m_BuildMenuActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ToggleBuildMenu.started += instance.OnToggleBuildMenu;
                @ToggleBuildMenu.performed += instance.OnToggleBuildMenu;
                @ToggleBuildMenu.canceled += instance.OnToggleBuildMenu;
            }
        }
    }
    public BuildMenuActions @BuildMenu => new BuildMenuActions(this);
    public interface IBuildMenuActions
    {
        void OnToggleBuildMenu(InputAction.CallbackContext context);
    }
}
